### ISSUE TITLE
Question: use of a rs485 chain

### ISSUE THREAD

**Issue by FulvioSpelta** [RoanBrand/SerialToTCPBridgeProtocol#1]
Hi,  is it possibile to use rs485 chain to connect multiple arduino to 1 host (raspberry) using 1 serial on host?

I have multiple devices (up to 16) and it will be wonderful connect all pf them (or a subset) to the host using a rs485 chain like modbus devices.

Thanks for your time
f

**Comment by RoanBrand** [comment]
Hi

It is possible but it would be awkward.
The protocol requires the interface to be full duplex. That you can do with 4 wires but even then it would need the capability for every client to send data to the gateway when it wants to without collision with other clients.

It will need another layer to be built on top of the interface that either:

- works like the master-slave relationship as modbus. The gateway will continually poll each client to check if there is any data it wants to send along. With this option it is not needed to go full duplex (4 wires)
- or does some collision avoidance/detection when multiple clients want to send data.

It would certainly be great to have many devices be able to connect to the internet with such a low total cost.

**Comment by FulvioSpelta** [comment]
Thanks a lot for your reply.
Your notes remind me of the old token ring LAN where each node could transmit only if it had the token. :-)

Maybe that the second solution (collision avoidance) could be simpler to implement into existing code and maybe it can have good performance in small networks.

I'm sorry but my confidence with C and GO is poor and i'm not able to support this idea in the near time.
If someone wants to try I'm available for testing.
Thanks again for your time (you can close the issue whenever you like)

**Comment by RoanBrand** [comment]
Hi

Thanks! I would really like to try this sometime. Implementing collision avoidance should not take too long.
Can even maybe utilize some existing stuff, e.g. https://github.com/MichaelJonker/HardwareSerialRS485

I cannot give you an ETA unfortunately, as I also need to get some 485 interfaces to play with.
